spring:
  application:
    name: learn-dev

  data:
    mongodb:
      # uri: mongodb://admin:admin_password@127.0.0.1:27018/learndev?authSource=admin
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${LEARNDEV_MONGO_DB_NAME}?authSource=admin

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Database Connection Configuration
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  datasource:
    # url: jdbc:postgresql://127.0.0.1:5433/learndev
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${LEARNDEV_DB_NAME}
    username: ${LEARNDEV_DB_USER}
    password: ${LEARNDEV_DB_PASSWORD}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Hibernate (ORM) Configuration
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  jpa:
    drop-first: false    # Never drop the database
    show-sql: false
    hibernate:
      ddl-auto: validate # Ensure the database and its schema are in sync

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Database schema change manager
  # See:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: false

# ~~~~~~~~~~~~~~~~~~
# Logging Level
# ~~~~~~~~~~~~~~~~~~
logging:
  level:
    org.springframework: INFO
