#!/usr/bin/env python3
"""Generate the "Color palettes" Mermaid diagrams from the theme CSS.

Reads the design tokens straight from the two theme stylesheets (the source
of truth) and prints a Markdown section containing one Mermaid `block-beta`
swatch grid per theme and mode. GitHub renders Mermaid natively, so the
palette is visible in the browser without committing any image.

Each swatch is filled with the token's color; the label color (dark or
light) is chosen by WCAG relative luminance so the token name stays
readable on its own swatch.

Usage: python3 scripts/generate_palette_diagrams.py
Paste the output over the "Color palettes" section of
docs/design/theme-exploration.md whenever a token changes.
"""

import re
import sys

THEMES = [
    ("Catppuccin", "src/main/resources/static/css/theme-catppuccin.css",
     "Latte (light)", "Mocha (dark)"),
    ("Soft Paper", "src/main/resources/static/css/theme-soft-paper.css",
     "light", "dark"),
]

COLUMNS = 5

TOKEN_RE = re.compile(r"^\s*(--[a-z-]+)\s*:\s*(#[0-9a-fA-F]{3,6})\s*;")


def parse_blocks(path: str) -> tuple[dict[str, str], dict[str, str]]:
    """Return (light, dark) ordered token->hex maps from a theme stylesheet.

    The light palette is the first `:root` block; the dark palette is the
    `:root` inside `@media (prefers-color-scheme: dark)`.
    """
    light: dict[str, str] = {}
    dark: dict[str, str] = {}
    in_dark = False
    for line in open(path):
        if "prefers-color-scheme: dark" in line:
            in_dark = True
        match = TOKEN_RE.match(line)
        if match:
            (dark if in_dark else light)[match.group(1)] = match.group(2).lower()
    return light, dark


def luminance(hex_color: str) -> float:
    """WCAG relative luminance of a #rrggbb color."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    channels = []
    for i in (0, 2, 4):
        c = int(hex_color[i:i + 2], 16) / 255
        channels.append(c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4)
    r, g, b = channels
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def label_color(background: str) -> str:
    """Dark label on light swatches, light label on dark ones."""
    return "#11111b" if luminance(background) > 0.35 else "#f8f8f8"


def diagram(tokens: dict[str, str]) -> str:
    """A flowchart whose disconnected rows stack vertically: each row is a
    chain of COLUMNS nodes joined by invisible links (~~~). block-beta would
    be the natural fit but it ignores the label color, which makes dark
    swatches unreadable; flowchart honors it."""
    lines = ["```mermaid", "flowchart LR"]
    ids = []
    row: list[str] = []
    for index, (token, value) in enumerate(tokens.items()):
        short = token.removeprefix("--color-").removeprefix("--")
        block_id = f"t{index}"
        ids.append((block_id, value))
        row.append(f'{block_id}["{short}<br/>{value}"]')
        if len(row) == COLUMNS:
            lines.append("  " + " ~~~ ".join(row))
            row = []
    if row:
        lines.append("  " + " ~~~ ".join(row))
    for block_id, value in ids:
        lines.append(
            f"  style {block_id} fill:{value},stroke:#7f7f7f,"
            f"color:{label_color(value)}")
    lines.append("```")
    return "\n".join(lines)


def main() -> int:
    print("## Color palettes")
    print()
    print("<!-- Generated by scripts/generate_palette_diagrams.py from the")
    print("     theme stylesheets. Regenerate after any token change. -->")
    print()
    print("Every swatch below comes straight from the theme stylesheets;")
    print("GitHub renders these Mermaid blocks with the real colors, so no")
    print("image is committed. Values are the shipped (contrast-adjusted)")
    print("tokens, not the upstream palettes.")
    for name, path, light_label, dark_label in THEMES:
        light, dark = parse_blocks(path)
        for label, tokens in ((light_label, light), (dark_label, dark)):
            print()
            print(f"### {name} {label}")
            print()
            print(diagram(tokens))
    return 0


if __name__ == "__main__":
    sys.exit(main())
